package collection;


import org.w3c.event.*;

public class ManagerTableRow1 extends Template { 
	<%
	<tr style.backgroundColor={Binding property="selected" mode="TwoWay"} onclick="click">
		<td>
			<input type="text" value = {Binding property="name" mode="TwoWay" trigger="PropertyChanged"}/>
		</td> 

	</tr>   
	%> 
	public ManagerTableRow1(Bindable parent) { 
		super(parent);
	}

	MouseEventHandler click = (MouseEvent e) ->{
		alert("sasas");
	};
}
