package collection;

public class XAxis extends Template{
	<%
		<Iterator begin=30 end = 300 step = 50 xmlns:svg = "http://www.w3.org/2000/svg">
			<svg:text x={Binding property="index" context="status" converterTo="converte"} y=200>2001</text>
		</Iterator>
	%>
	protected XAxis(Bindable parent) {
		super(parent);
		
	}
	
	public ConverterFunction converte = (Object data)->{
		return 30+(int)data*50;
	};

}
