
public class Test implements Page{
	<%
	<html >
	<head>
	    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	    <title>CSS3/Lark Clock demo</title>
	    <link rel="stylesheet" type="text/css" href="css/clock.css" media="screen, projection" />
	</head>
	
	<script>
	kahsjkahskajhs
	</script>

	<body>

	    <div id="demo-top-bar">
		  <div id="demo-bar-inside">
		    <h2 id="demo-bar-badge">
		      <a href="/">Lark CSS-Tricks Example</a>
		    </h2>
		    <div id="demo-bar-buttons">
	        </div>
		  </div>
		</div>
	    <p><a href="/css3-clock/">&lt; 模拟钟表</a></p>
		<ul id="clock">	
		   	<li id="sec" x:name="sec"></li>
		   	<li id="hour" x:name="hour"></li>
			<li id="min" x:name="min"></li>
		</ul>
		
		<!--
		<svg width="320" height="320" xmlns="http://www.w3.org/2000/svg">
		  <g> 
		    <text font-family="microsoft yahei" font-size="120" y="160" x="160">马</text>
		    <animateTransform attributeName="transform" begin="0s" dur="10s" type="rotate" from="0 160 160" to="360 160 160" repeatCount="indefinite"/>
		  </g>
		</svg>
		-->
	</body>
</html>
	%>
	
	String name;
}
